environment:
  matrix:
    - nodejs_version: "8"
    #- nodejs_version: "7"
    #- nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run build
  - ls -al dist
  - npm run test

build: off

cache:
- node_modules
